os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "13"
    - nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - git submodule update --init --recursive
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test

cache:
- '%APPDATA%\npm-cache'
