[package]
name = "compiler"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "bench"
path = "bench.rs"

[dependencies]
# need to pin this version for Node 10 support
wasm-bindgen = "=0.2.60"
nom = "6.0.0"
web-sys = { version = "0.3", features = ["console"] }
lazy_static = "1.4.0"
json = "0.12.4"
console_error_panic_hook = "0.1.6"
# need this rev for nom 6 and Hash support
nom_locate = { git = "https://github.com/fflorent/nom_locate", rev = "1146a10c66c3c676fd78dac280641179c1395a07" }
aho-corasick = "0.7.15"

[dev-dependencies]
pretty_assertions = "0.6.1"
