[package]
name = "compiler"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
# need to pin this version for Node 10 support
wasm-bindgen = "=0.2.60"
benchpress_sys = { path = "../benchpress_sys" }
